# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git, osx, python, brew, django, gpg-agent, pip, perl)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export EDITOR='vi'
export PATH=/usr/local/share/npm/bin:/usr/local/share/python:/usr/local/bin:$HOME/Applications/bin:$PATH
export WORKON_HOME=$HOME/.virtualenvs
export LC_CTYPE="en_US.UTF-8"

if [[ -r /usr/local/share/python/virtualenvwrapper.sh ]]; then
    source /usr/local/share/python/virtualenvwrapper.sh
else
    echo "WARNING: Can't find virtualenvwrapper.sh"
fi

alias tmux='tmux -u'
alias t='tmux.py'
alias reKill='reKill.py'
alias pysmtp='python -m smtpd -n -c DebuggingServer localhost:1025'
alias resetterminal='echo -n -e "\033]0;\007"'
alias gitpretty="git log --pretty=format:'%h : %Cblue%aN%Creset : %Cred%d%Creset : %s' --graph"
alias vi='mvim -v'
alias vim='mvim -v'
alias sudovi='sudo vi -u NONE'
alias aws_bmsilva='envdir ~/Lab/AWS/bmsilva/botoenv ~/.virtualenvs/sys/bin/python ~/Lab/AWS/bmsilva/aws.py'

source ~/perl5/perlbrew/etc/bashrc
