export EDITOR='vi'
export WORKON_HOME=$HOME/.virtualenvs
export LC_CTYPE="en_US.UTF-8"
export LANG="en_US.UTF-8"

alias tmux='tmux -u'
alias t='tmux.py'
alias reKill='reKill.py'
alias pysmtp='python -m smtpd -n -c DebuggingServer localhost:1025'
alias resetterminal='echo -n -e "\033]0;\007"'
alias gitpretty="git log --pretty=format:'%h : %Cblue%aN%Creset : %Cred%d%Creset : %s' --graph"

alias ls='ls -G'
alias ll='ls -lG'

if [[ -r $HOME/.host_nickname ]]; then
    HOST_NICKNAME=`cat ${HOME}/.host_nickname`
else
    HOST_NICKNAME=`hostname -s`
fi

export PS1="\u@${HOST_NICKNAME}:\W \$ "

if [[ -r $HOME/.${HOST_NICKNAME}_bash_profile ]]; then
    source $HOME/.${HOST_NICKNAME}_bash_profile
else
    echo "WARNING: Can't find custom bash_profile"
fi
